function [feature_vec] = geometric_features(bw)


labeledImage = bwlabel(bw);
measurements = regionprops(labeledImage,...
    'BoundingBox','Eccentricity','Extent','Solidity',...
    'Area' ,'Perimeter',...
    'Orientation','EulerNumber');

measurements = measurements(1);

feature_vec = [measurements.Eccentricity,...
    measurements.Extent,...
    measurements.Solidity,...
    measurements.Perimeter/measurements.Area,...
    measurements.Orientation,...
    measurements.EulerNumber,...
    size(bw,1)/size(bw,2)
]';


% features(7) = 4*pi*measures.Area./(measures.Perimeter.^2);
% % roundness
% features(8) = (4*measures.Area)./(pi*(measures.MajorAxisLength.^2));



