function [feature_vec] = geometric_features(bw)


labeledImage = bwlabel(bw);
measurements = regionprops(labeledImage,...
    'BoundingBox','Eccentricity','Extent','Solidity',...
    'Area' ,'Perimeter',...
    'Orientation','EulerNumber','MajorAxisLength');

measurements = measurements(1);

%     measurements.EulerNumber,...
feature_vec = [measurements.Eccentricity,...
    measurements.Extent,...
    measurements.Solidity,...
    measurements.Perimeter/measurements.Area,...
    measurements.Orientation/90.0,...
    size(bw,1)/size(bw,2),... % aspect ration
    (4*measurements.Area)./(pi*(measurements.MajorAxisLength.^2)),... % roundness
    4*pi*measurements.Area./(measurements.Perimeter.^2)... % circularity
]';


% features(7) = 4*pi*measures.Area./(measures.Perimeter.^2);
% % roundness
% features(8) = (4*measures.Area)./(pi*(measures.MajorAxisLength.^2));



